import { NextResponse } from 'next/server';
import { createServiceSupabase } from '@/lib/supabase/server';
import { REFERRAL_CHARS } from '@/lib/referral-code';

// GET /api/referrals/lookup?code=<CODE> — public, no auth (ticket 0021).
//
// Resolves a referral code → the inviting coach's FIRST NAME so the signup page
// can land warm ("Coach Sarah invited you") instead of anonymous. This is the
// ONLY thing the response exposes: no email, no full name, no coach id, no team
// or player data (AGENTS.md COPPA / data-minimization).
//
// Hardening against enumeration: an empty / malformed code returns
// { coachFirstName: null } WITHOUT a DB scan, and an unknown-but-well-formed code
// returns the same graceful null (NOT a 404) so a bad / stale link never breaks
// signup. The endpoint never confirms a code's validity beyond returning a name.
//
// Resolution reuses the SAME deterministic mapping makeReferralCode produces
// everywhere else: codes are stored on coaches.preferences.referral_code (lazily
// generated by /api/referrals and /api/team-card). We match the STORED code with
// a single lookup — no full-table recompute, no new code-index table.

// A well-formed code is exactly 6 chars from the referral alphabet (see
// src/lib/referral-code.ts). Rejecting anything else BEFORE touching the DB
// avoids a scan on garbage input.
const CODE_RE = new RegExp(`^[${REFERRAL_CHARS}]{6}$`);

export async function GET(request: Request) {
  const code = (new URL(request.url).searchParams.get('code') ?? '')
    .trim()
    .toUpperCase();

  // Empty or malformed → graceful null, no DB scan.
  if (!CODE_RE.test(code)) {
    return NextResponse.json({ coachFirstName: null });
  }

  try {
    const supabase = await createServiceSupabase();

    // Single lookup against the STORED referral code. Select ONLY full_name so we
    // never pull (let alone expose) email / id / team / player data.
    const { data: coach } = await supabase
      .from('coaches')
      .select('full_name')
      .eq('preferences->>referral_code', code)
      .limit(1)
      .maybeSingle();

    const fullName = (coach?.full_name as string | null | undefined) ?? null;
    const coachFirstName = fullName ? fullName.trim().split(/\s+/)[0] || null : null;

    return NextResponse.json({ coachFirstName });
  } catch {
    // A bad / stale code must never break signup — degrade to the generic banner.
    return NextResponse.json({ coachFirstName: null });
  }
}
